name: CI - appwrite - Soutenance

on:
  push:
    branches: [ "master", "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0'
      - name: Setup Appwrite CLI
        uses: appwrite/setup-for-actions@v1
        with:
          endpoint: 'https://localhost:83/v1'
          project: '63cede4a4747ce750b8a'
          key: '${{ secrets.APPWRITE_API_KEY }}'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Deploy
        run: |
          appwrite functions createTag \
            --functionId="60292830c4571" \
            --command="dotnet appwrite-dotnet-function-example.dll" \
            --code="bin/Release/net5.0/" 
